//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeCharmSearcher.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiegeCharmSearcher.Shared.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm Added: {0} {1}.
        /// </summary>
        internal static string AddedCharm {
            get {
                return ResourceManager.GetString("AddedCharm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already on the Selected Charm.
        /// </summary>
        internal static string AlreadySamePlace {
            get {
                return ResourceManager.GetString("AlreadySamePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Detect Position.
        /// </summary>
        internal static string FailedToDetectPosition {
            get {
                return ResourceManager.GetString("FailedToDetectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating from Specified Position: {0}.
        /// </summary>
        internal static string NavigatingFrom {
            get {
                return ResourceManager.GetString("NavigatingFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to {0}.
        /// </summary>
        internal static string NavigatingTo {
            get {
                return ResourceManager.GetString("NavigatingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Done.
        /// </summary>
        internal static string NavigationDone {
            get {
                return ResourceManager.GetString("NavigationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoneCharm {
            get {
                return ResourceManager.GetString("NoneCharm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Count: {0}.
        /// </summary>
        internal static string RetryCount {
            get {
                return ResourceManager.GetString("RetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SKIPPED).
        /// </summary>
        internal static string SkippedCharm {
            get {
                return ResourceManager.GetString("SkippedCharm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping.
        /// </summary>
        internal static string Skipping {
            get {
                return ResourceManager.GetString("Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing on {0} {1}.
        /// </summary>
        internal static string StandingOn {
            get {
                return ResourceManager.GetString("StandingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Stopped.
        /// </summary>
        internal static string StoppedAnalyzing {
            get {
                return ResourceManager.GetString("StoppedAnalyzing", resourceCulture);
            }
        }
    }
}
